version: 2 

models:
  - name: stg_orders 
    columns: 
    - name: order_id 
      tests:
        - not_null
        - unique
    - name: customer_id 
      tests:
        - not_null
        - relationships: 
            arguments:
              to: ref('stg_customers')
              field: customer_id
    
    - name: order_status 
      tests:
        - accepted_values:
            arguments:
              values: ['delivered', 'shipped', 'canceled', 'invoiced', 'processing', 'unavailable', 'approved', 'created']




  - name: stg_customers 
    columns: 
    - name: customer_id 
      tests:
        - not_null
        - unique

  - name: stg_products 
    columns: 
    - name: product_id 
      tests:
        - not_null
        - unique

  - name: stg_sellers 
    columns: 
    - name: seller_id 
      tests:
        - not_null
        - unique

  - name: stg_order_items 
    columns: 
    - name: order_id 
      tests:
        - not_null
        - relationships: 
            arguments:
              to: ref('stg_orders')
              field: order_id
    - name: product_id 
      tests:
        - not_null
        - relationships: 
            arguments:
              to: ref('stg_products')
              field: product_id
    - name: seller_id 
      tests:
        - not_null
        - relationships: 
            arguments:
              to: ref('stg_sellers')
              field: seller_id